# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: magicjar
slogan: Your one-stop cookding solution.
email: fajarsetya@live.com
description: >- # this means to ignore newlines until "baseurl:"
  Seorang pembuat website, game, dll yang siap dan ingin berbagi untuk siapa saja.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://magicjar.github.io" # the base hostname & protocol for your site, e.g. http://example.com
copyright: "&copy; 2020 | FJRSTY."
date_format: "%-d %b %Y"
lang: id

# Analytics setting
google_analytics_id:

# Post settings
permalink: /blog/:year/:month/:title
paginate: 2
paginate_path: /blog/page:num/
disqus: magicjar
      
# Homepage settings
show_excerpts: true
post_limit: 3

# Additional pages
show_blog: true
show_portfolio: true
show_resume: true

# Collections
collections:
  portfolios:
    output: false
    permalink: /:collection/:name
  fun:
    output: false
    permalink: /:collection/:name

# Build settings
markdown: kramdown
kramdown:
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
sass:
  sass_dir: _sass
  style: compressed

include:
  - node_modules

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
